In [16]:
import numpy as np
        

### Bubble Sort

In [17]:
def BubbleSort(vetor):
    n = len(vetor)
    
    for i in range(n):
        for j in range(0, n - i - 1):
            if vetor[j] > vetor[j +1]:
                temp = vetor[j]
                vetor[j] = vetor[j+1]
                vetor[j+1] = temp
    return vetor

In [18]:
BubbleSort(np.array([55,44,12,35,2,45,32]))

array([ 2, 12, 32, 35, 44, 45, 55])

### Selection Sort

In [19]:
def SelectionSort(vetor):
    n = len(vetor)
    for i in range(n):
        id_minimo = i
        for j in range(i+1,n):
            if vetor[id_minimo] > vetor[j]:
                id_minimo = j
        temp = vetor[i]
        vetor[i] = vetor[id_minimo]
        vetor[id_minimo] = temp
    return vetor

In [20]:
SelectionSort(np.array([55,44,12,35,2,45,32]))

array([ 2, 12, 32, 35, 44, 45, 55])

### Insertion Sort

In [21]:
def InsertionSort(vetor):
    n = len(vetor)
    for i in range(1,n):
        marcado = vetor[i]
        j = i - 1
        while j >= 0 and marcado < vetor[j]:
            vetor[j+1] = vetor[j]
            j -= 1
        vetor[j+1] = marcado
    return vetor

In [22]:
InsertionSort(np.array([55,44,12,35,2,45,32]))

array([ 2, 12, 32, 35, 44, 45, 55])

### Shell Sort

In [23]:
def ShellSort(vetor):
    intervalo = len(vetor) // 2
    
    while intervalo > 0:
        for i in range(intervalo, len(vetor)):
            temp = vetor[i]
            j = i
            while j >= intervalo and vetor[j - intervalo] > temp:
                vetor[j] = vetor[j - intervalo]
                j -= intervalo
            vetor[j] = temp
        intervalo //= 2
    return vetor

In [24]:
ShellSort(np.array([55,44,12,35,2,45,32]))

array([ 2, 12, 32, 35, 44, 45, 55])

### Merge Sort

In [25]:
def MergeSort(vetor):
    if len(vetor) > 1:
        divisao = len(vetor) // 2
        esquerda = vetor[:divisao].copy()
        direita = vetor[divisao:].copy()
        
        MergeSort(esquerda)
        MergeSort(direita)
        i = j = k = 0
        
        while i < len(esquerda) and j < len(direita):
            if esquerda[i] < direita[j]:
                vetor[k] = esquerda[i]
                i += 1
            else:
                vetor[k] = direita[j]
                j += 1
            k += 1
        while i < len(esquerda):
            vetor[k] = esquerda[i]
            i += 1
            k += 1
        while j < len(direita):
            vetor[k] = direita[j]
            j += 1
            k += 1
    return vetor

In [26]:
MergeSort(np.array([55,44,12,35,2,45,32]))

array([ 2, 12, 32, 35, 44, 45, 55])

### Quick Sort

In [27]:
def particao(vetor,inicio,final):
    pivo = vetor[final]
    i = inicio - 1
    for j in range(inicio,final):
        if vetor[j] <= pivo:
            i += 1
            vetor[i], vetor[j] = vetor[j], vetor[i]
    vetor[i+1], vetor[final] = vetor[final], vetor[i+1]
    return i + 1

def QuickSort(vetor, inicio, final):
    if inicio < final:
        posicao = particao(vetor,inicio,final)
        QuickSort(vetor, inicio, posicao -1)
        QuickSort(vetor, posicao+1, final)
    return vetor

In [28]:
vetor = np.array([55,44,12,35,2,45,32])
QuickSort(vetor, 0, len(vetor) - 1)

array([ 2, 12, 32, 35, 44, 45, 55])

### Desempenho

In [29]:
import random
randomlist = random.sample(range(0,5000),5000)


In [30]:
%timeit BubbleSort(randomlist)

462 ms ± 5.45 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [31]:
%timeit SelectionSort(randomlist)

332 ms ± 9.08 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [32]:
%timeit InsertionSort(randomlist)

313 µs ± 4.92 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [33]:
%timeit ShellSort(randomlist)

3.02 ms ± 75.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [34]:
%timeit MergeSort(randomlist)

5.62 ms ± 141 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [36]:
%timeit QuickSort(randomlist,0,len(vetor)-1)

2.72 µs ± 172 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
