In [3]:
import numpy as np
        

### Bubble Sort

In [2]:
def BubbleSort(vetor):
    n = len(vetor)
    
    for i in range(n):
        for j in range(0, n - i - 1):
            if vetor[j] > vetor[j +1]:
                temp = vetor[j]
                vetor[j] = vetor[j+1]
                vetor[j+1] = temp
    return vetor

In [4]:
BubbleSort(np.array([55,44,12,35,2,45,32]))

array([ 2, 12, 32, 35, 44, 45, 55])

### Selection Sort

In [5]:
def SelectionSort(vetor):
    n = len(vetor)
    for i in range(n):
        id_minimo = i
        for j in range(i+1,n):
            if vetor[id_minimo] > vetor[j]:
                id_minimo = j
        temp = vetor[i]
        vetor[i] = vetor[id_minimo]
        vetor[id_minimo] = temp
    return vetor

In [6]:
SelectionSort(np.array([55,44,12,35,2,45,32]))

array([ 2, 12, 32, 35, 44, 45, 55])

### Insertion Sort

In [1]:
def InsertionSort(vetor):
    n = len(vetor)
    for i in range(1,n):
        marcado = vetor[i]
        j = i - 1
        while j >= 0 and marcado < vetor[j]:
            vetor[j+1] = vetor[j]
            j -= 1
        vetor[j+1] = marcado
    return vetor

In [3]:
InsertionSort(np.array([55,44,12,35,2,45,32]))

array([ 2, 12, 32, 35, 44, 45, 55])

### Shell Sort

In [4]:
def ShellSort(vetor):
    intervalo = len(vetor) // 2
    
    while intervalo > 0:
        for i in range(intervalo, len(vetor)):
            temp = vetor[i]
            j = i
            while j >= intervalo and vetor[j - intervalo] > temp:
                vetor[j] = vetor[j - intervalo]
                j -= intervalo
            vetor[j] = temp
        intervalo //= 2
    return vetor

In [6]:
ShellSort(np.array([55,44,12,35,2,45,32]))

array([ 2, 12, 32, 35, 44, 45, 55])

### Merge Sort

In [7]:
def MergeSort(vetor):
    if len(vetor) > 1:
        divisao = len(vetor) // 2
        esquerda = vetor[:divisao].copy()
        direita = vetor[divisao:].copy()
        
        MergeSort(esquerda)
        MergeSort(direita)
        i = j = k = 0
        
        while i < len(esquerda) and j < len(direita):
            if esquerda[i] < direita[j]:
                vetor[k] = esquerda[i]
                i += 1
            else:
                vetor[k] = direita[j]
                j += 1
            k += 1
        while i < len(esquerda):
            vetor[k] = esquerda[i]
            i += 1
            k += 1
        while j < len(direita):
            vetor[k] = direita[j]
            j += 1
            k += 1
    return vetor

In [8]:
MergeSort(np.array([55,44,12,35,2,45,32]))

array([ 2, 12, 32, 35, 44, 45, 55])

### Quick Sort

In [9]:
def particao(vetor,inicio,final):
    pivo = vetor[final]
    i = inicio - 1
    for j in range(inicio,final):
        if vetor[j] <= pivo:
            i += 1
            vetor[i], vetor[j] = vetor[j], vetor[i]
    vetor[i+1], vetor[final] = vetor[final], vetor[i+1]
    return i + 1

def QuickSort(vetor, inicio, final):
    if inicio < final:
        posicao = particao(vetor,inicio,posicao-1)
        QuickSort(vetor, posicao+1, final)
    return vetor

In [ ]:
vetor = np.array([55,44,12,35,2,45,32])
QuickSort(vetor, 0, len(vetor) - 1)